import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

const ButtonCustom = ({ text }: { text: string }) => {
  return (
    <button className='border border-gray-300 rounded shadow text-lg px-4 py-6'>{text}</button>)
}

const Home: NextPage = () => {
  const [valuesList, setValuesList] = useState([
    "#D3F99D",
    "#CC6666",
    "#5E597E",
    "#FF7E00",
  ])

  return (
    <div>
      <Head>
        <title>Hext picker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='min-h-screen flex justify-center items-center'>
        <div className='max-w-lg flex flex-col justify-center items-center gap-6 border border-gray-100 shadow-lg p-8'>
          <div className={`bg-teal-200 w-80 h-80`} />
          <div className='w-full grid grid-cols-2 gap-8'>
            {valuesList.map(item => (
              <ButtonCustom text={item} key={item} />
            ))}
          </div>
        </div>

      </div>
    </div>
  )
}

export default Home
